version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flightbooking
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: flight_app
    ports:
      - "3010:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: npm run start:dev

volumes:
  postgres_data:
